apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-analysis-step
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-analysis-step
  template:
    metadata:
      labels:
        app: rollout-analysis-step
    spec:
      containers:
      - name: rollouts-demo
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
  strategy:
    blueGreen: 
      activeService: rollout-analysis-step
      previewService: rollout-analysis-step-preview
      autoPromotionSeconds: 300
      prePromotionAnalysis:
        args:
        - name: stable-hash
          valueFrom:
            podTemplateHashValue: Stable
        - name: latest-hash
          valueFrom:
            podTemplateHashValue: Latest
        templates:
        - templateName: pass
    # canary:
    #   # maxSurge: 1
    #   # maxUnavailable: 0
    #   steps:
    #   - setWeight: 30
    #   - pause: { duration: 30s }
    #   - setWeight: 60
    #   - pause: { duration: 30s }
    #   - setWeight: 100
    #   - pause: { duration: 10s }
    #   - analysis:
    #       args:
    #       - name: stable-hash
    #         valueFrom:
    #           podTemplateHashValue: Stable
    #       - name: latest-hash
    #         valueFrom:
    #           podTemplateHashValue: Latest
    #       templates:
    #       - templateName: pass
