apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-analysis-step
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-analysis-step
  template:
    metadata:
      labels:
        app: rollout-analysis-step
    spec:
      containers:
      - name: rollouts-demo
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
  strategy:
    blueGreen: 
      activeService: rollout-analysis-step
      previewService: rollout-analysis-step-preview
      autoPromotionSeconds: 300
      prePromotionAnalysis:
        args:
        - name: stable-hash
          valueFrom:
            podTemplateHashValue: Stable
        - name: latest-hash
          valueFrom:
            podTemplateHashValue: Latest
        metrics:
        - name: pass
          count: 1
          interval: 5s
          failureLimit: 1
          provider:
            job:
              spec:
                template:
                  spec:
                    containers:
                    - name: sleep
                      image: alpine:3.8
                      command: [sh, -c, 'echo "STABLE-HASH: {{ "{{" }} args.stable-hash {{ "}}" }},LATEST-HASH:{{ "{{" }}args.latest-hash{{ "}}" }}"']
                    - name: curl
                      image: alpine/curl
                      command: ["sh", "-c", "for i in $(seq 1 20); do curl rollout-analysis-step-preview; sleep 1; done"]
                    restartPolicy: Never
                backoffLimit: 0
    # canary:
    #   # maxSurge: 1
    #   # maxUnavailable: 0
    #   steps:
    #   - setWeight: 30
    #   - pause: { duration: 30s }
    #   - setWeight: 60
    #   - pause: { duration: 30s }
    #   - setWeight: 100
    #   - pause: { duration: 10s }
    #   - analysis:
    #       args:
    #       - name: stable-hash
    #         valueFrom:
    #           podTemplateHashValue: Stable
    #       - name: latest-hash
    #         valueFrom:
    #           podTemplateHashValue: Latest
    #       templates:
    #       - templateName: pass
